# 网站基础配置
baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = '东湖居士'
theme = 'reimu'

# CJK 语言支持
[languages]
  [languages.zh-cn]
    weight = 1
    hasCJKLanguage = true

# ----------------------------------------------------
# 主题功能配置区
# ----------------------------------------------------

# [params] 表格，用于设置作者等基本参数
[params]
author = "东湖居士"

# [params.features.pjax] 表格，用于开启 Pjax 功能
# 这个表格定义了 params -> features -> pjax 的嵌套结构
[params.features.pjax]
enable = true

# [params.music] 表格，用于配置音乐播放器
# 这个表格定义了 params -> music 的嵌套结构
[params.music]
enable = true
server = "netease"
type = "playlist"
id = "7232039344"



[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

# 代码块的正常显示
[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true



