# 工作流的名称
name: Deploy Hugo site to Pages

# 触发条件：当有代码推送到 main 分支时自动运行
on:
  push:
    branches:
      - main  # 如果您的主分支是 master，请改成 master
  workflow_dispatch:

# 设置任务的默认权限
permissions:
  contents: read
  pages: write
  id-token: write

# 设置并发控制，防止同时运行多个相同的任务
concurrency:
  group: "pages"
  cancel-in-progress: true

# 定义一个名为 "deploy" 的任务
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出您的代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # 第二步：安装Hugo环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # 第三步：构建网站
      - name: Build
        run: hugo --minify

      # 第四步：部署到GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v4
